[project]
name = "forecasting-service"
version = "0.0.1"
requires-python = ">=3.11,<3.12"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
python-dotenv = "^1.2.1"
numpy = "^2.3.5"
